### PR TITLE
Better error reporting, gevent 1.1 compatibility

### PR DESCRIPTION
**Pull request by jikamens**

### CODE REVIEW

**Comment by ddudnik** [comment]
Hi @dvdotsenko !

Is there any chance that at least d43d0218818a298807f2c3728119faeb8b3eadcb gonna be merged? It would really help to resolve issues when using jsonrpc with gevent > 1.1. See this page for details http://www.gevent.org/whatsnew_1_1.html#compatibility, section about 'gevent.pywsgi.WSGIServer'.

Thanks,
Denis

**Comment by dvdotsenko** [comment]
Looking at it. Appreciate your help in keeping this piece of software
functional.

**Comment by dvdotsenko** [comment]
Dig it. Will merge and push out a new build later today. Thank you much.

**Comment by dvdotsenko** [comment]
Sorry for delay. Build 0.4.1 with the above changes was released.

**Pull request merged**
